name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: |
            ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/mern_app/frontend
            
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            
            # pull changes from frontend repo
            git pull origin main
            
            # Install dependencies
            npm install
            
            # Build the frontend
            npm run build
            
            # (Optional)
            # pm2 restart frontend
            
            echo "Deployment complete"
